package edu.ufl.cise.plcsp23;

import org.junit.internal.builders.NullBuilder;

public class StringLitToken extends Token implements IStringLitToken  {

    public StringLitToken(int pos, int length, int line, int col, char[] source){
        super(Kind.STRING_LIT, pos, length, source);
    
    }

    @Override
    public String getValue() {
String value ="";
        // TODO Auto-generated method stub

        /*
         * FIX: return source, but procesed to not include quotation marks or escape sequences
         * return a string generated by procesing a character array - the function for this is String.valueOf()
         */

         for(int i = pos+1; i<length-1; i++){
            value = value + source[i];
         }
        // String value = String.valueOf(source);
        // value = value.substring(pos+1, (pos+1)+(length-2));
        // return value;
        return value;
    }

    @Override
    public SourceLocation getSourceLocation() {
        // TODO Auto-generated method stub
        return new SourceLocation(1,1);
    }

    @Override
    public Kind getKind() {
        // TODO Auto-generated method stub
        return kind;
    }

    @Override
    public String getTokenString() {
        // TODO Auto-generated method stub
        String withQoutes = String.valueOf(source);
        withQoutes = withQoutes.substring(pos, (pos)+(length));

    return withQoutes;
    }
}